-keep class com.google.devtools.build.android.desugar.runtime.** { *; }
-keep class io.agora.** { *; }
-keep class io.agora.base.internal.Logging { *; }
-dontwarn com.google.devtools.build.android.desugar.runtime.ThrowableExtension
